{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"Expected\n    <*shell.ErrWithCmdOutput | 0xc0000172f0>: {\n        Underlying: <*exec.ExitError | 0xc00040f740>{\n            ProcessState: {\n                pid: 6902,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 399528},\n                    Stime: {Sec: 0, Usec: 150079},\n                    Maxrss: 107940,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 7767,\n                    Majflt: 35,\n                    Nswap: 0,\n                    Inblock: 16680,\n                    Oublock: 20624,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 2387,\n                    Nivcsw: 2485,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Warning: resource secrets/kubeslice-license-file is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.\",\n                        \"Error from server (Conflict): error when applying patch:\",\n                        \"{\\\"data\\\":{\\\"license-created\\\":\\\"MjAyMy0wOS0wNVQwNzo0NTowNC45NTFadGFtcGVyaW5nX2l0\\\",\\\"license-type\\\":\\\"a3ViZXNsaWNlLXRyaWFsLWxpY2Vuc2U=\\\"},\\\"metadata\\\":{\\\"annotations\\\":{\\\"kubectl.kubernetes.io/last-applied-configuration\\\":\\\"{\\\\\\\"apiVersion\\\\\\\":\\\\\\\"v1\\\\\\\",\\\\\\\"data\\\\\\\":{\\\\\\\"customer-name\\\\\\\":\\\\\\\"aG90IGhhd2s=\\\\\\\",\\\\\\\"grace-period\\\\\\\":\\\\\\\"NQ==\\\\\\\",\\\\\\\"license-created\\\\\\\":\\\\\\\"MjAyMy0wOS0wNVQwNzo0NTowNC45NTFadGFtcGVyaW5nX2l0\\\\\\\",\\\\\\\"license-expiration\\\\\\\":\\\\\\\"MjAyMy0wOS0xMlQwNzo0NTowNC45NTJa\\\\\\\",\\\\\\\"license-id\\\\\\\":\\\\\\\"OGFjMWM5OWQtNmUzOS00NGE5LTk2ZGEtYzM5MWJhN2Y4NmY4\\\\\\\",\\\\\\\"license-type\\\\\\\":\\\\\\\"a3ViZXNsaWNlLXRyaWFsLWxpY2Vuc2U=\\\\\\\",\\\\\\\"license-updated\\\\\\\":\\\\\\\"MjAyMy0wOS0wNVQwNzo0NTowNS4wODha\\\\\\\",\\\\\\\"license.key\\\\\\\":\\\\\\\"a2V5L2V5SmhZMk52ZFc1MElqcDdJbWxrSWpvaU1HSTJaRFk0WVdZdE9EazROaTAwTjJJd0xUbGpPVEV0WW1aaE1HRTFNMlJoWTJNekluMHNJbkJ5YjJSMVkzUWlPbnNpYVdRaU9pSm1OVE16TkdOalpDMWxaRGszTFRSaE1qUXRPRE16Wmkxak56bGxPR0ZtTWpRMllUWWlmU3dpY0c5c2FXTjVJanA3SW1sa0lqb2laVEZtTnpSak9ERXRZV1V5WXkwMFlqQTNMVGcxTnpndE16RTFPVFU1T0RZeVpqTTVJaXdpWkhWeVlYUnBiMjRpT2pZd05EZ3dNSDBzSW5WelpYSWlPbTUxYkd3c0lteHBZMlZ1YzJVaU9uc2lhV1FpT2lJNFlXTXhZems1WkMwMlpUTTVMVFEwWVRrdE9UWmtZUzFqTXpreFltRTNaamcyWmpnaUxDSmpjbVZoZEdWa0lqb2lNakF5TXkwd09TMHdOVlF3TnpvME5Ub3dOQzQ1TlRGYUlpd2laWGh3YVhKNUlqb2lNakF5TXkwd09TMHhNbFF3TnpvME5Ub3dOQzQ1TlRKYUluMTkuNmxqSVJ2dTFWbXNoNGU2Z1YzR25WNUN5VWg1QWhBWnpLMzJZYnpNRGstZFlOT1c2WDluVlU2SEdxNkVOaVpWR1RBLWhMR2VOREZ6VnYzU1pjSGtFQ1E9PQ==\\\\\\\",\\\\\\\"machine.file\\\\\\\":\\\\\\\"LS0tLS1CRUdJTiBNQUNISU5FIEZJTEUtLS0tLQpleUpsYm1NaU9pSlhhbEZVY0N0aFJrWTBSVFZHWTI4NVRXdzBaVE5FZVVwWlRIUXpaM1IzTXpkbWVGRXIKUVU1TlpXWkVTMjAzZDFwaE1HcFlaM1ZUTjFSb1lrbHZhbUZwZW1oWlZVUkZaRmwxYWl0R1ZGcG5NVFJsCmFHSkZLMEpKYjJOaVRubzFRVWhIYnpOaWEyOVZOMFZ3U0V0bGRFRXpORW8wWTIxMlVVUjNOVlpGWjFSVgpTM0JVWkhjclNIcFZUMWhHVFVVMmRtNXFWMHRyV1d0SFpWazNZbkp0TW01cVprTjNVVWRXUWxSdlNreDQKYkZoWE9IVmhhMHhaV0ZweVREWm1iV1JPZW5seVZqQjVXVTl3TUZKcVF6Um1VM0paYnpsaVFtWnBWVU5FClNIQTNURFpZWW0wcmRXWmpTMEUwU0hkd2RIQlZVaTlFWlVvelRGSXdTRXN3UTNWNU56SnlVMDFSZFdSTQpUbWxHUVVwbGVHZFpjR1pKZWxNMlIxUlpSM05TZDNkcU1qTkxVVUozVG5KU09XeHhRbXRRY0hrM1pFa3YKYldoeVkxaHZiRFpCVEU5a1pUZENVelpTVGpCMU1YZElXV1prUW1GNWVIVkljR1ZPTkhBd1YwSktTa3RPClZtdHJSbXd3YWxaVVoyTkhPV0ZWT0Uxb2VsUXJiWE0xTlhCMmJrMDFLMWhGZFRsNGQzUnRVa0Z2ZVV4UgpjRUo1VW5CNlRXZzVhWG8xYUM5UWFscE1lR3g2TVhkRGRtNHlXV053VWpSSlZFMURjWGd4YUN0Nk0yWmoKV0RsUlZrRlVXR2g1Y1RKNVkxUlNNbWx5U2tWbGFGUXhiSG8xZDBaRVkwSnFWRlU0V1dkRlNESnBNSFZ1CmJ6azRhekZDVVdrNWMwSnlRbWhoYzNSck56QjZaMjV5TjBRNVUzVmxPVVZoVVhsQlMyRTJUamRzYUhKeApjMHQ1WjB0eGVrWkxPVzh6V0ZCNmRGVjNVbTl1YjJWdWFGQldOMFl4UVVOUU1FaE1hRzV4Y1ZsMlkyRnEKVT...\n\nGomega truncated this representation as it exceeds 'format.MaxLength'.\nConsider having the object provide a custom 'GomegaStringer' representation\nor adjust the parameters in Gomega's 'format' package.\n\nLearn more here: https://onsi.github.io/gomega/#adjusting-output\n\nto be nil","children":[{"name":"[It] Validate License Tests License Validate tests Should revert back the fields in secret,in case someone tampered","uid":"f377fd06cab27a27","parentUid":"e3402378078db82eee76922a47a309ba","status":"failed","time":{"start":1693899867000,"stop":1693899908198,"duration":41198},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e3402378078db82eee76922a47a309ba"},{"name":"Timed out after 204.759s.\nExpected\n    <int>: 0\nto equal\n    <int>: 1","children":[{"name":"[It] E2E tests for license job > when license config is tampered with should not create new secret upon restart","uid":"4d43b553ced0d86d","parentUid":"464ea62cc2d73cb7c8885d35ef23e1fb","status":"failed","time":{"start":1693899867000,"stop":1693900151147,"duration":284147},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"464ea62cc2d73cb7c8885d35ef23e1fb"},{"name":"Unexpected error:\n    <*shell.ErrWithCmdOutput | 0xc0006de438>: {\n        Underlying: <*exec.ExitError | 0xc00063aa20>{\n            ProcessState: {\n                pid: 6812,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 380690},\n                    Stime: {Sec: 0, Usec: 155233},\n                    Maxrss: 102832,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 9687,\n                    Majflt: 9,\n                    Nswap: 0,\n                    Inblock: 12824,\n                    Oublock: 20624,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 1142,\n                    Nivcsw: 2835,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/slice/slice_event.yaml\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                    ],\n                },\n            },\n            stderr: {\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/slice/slice_event.yaml\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                ],\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/slice/slice_event.yaml\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                    ],\n                },\n            },\n            merged: {\n                Mutex: {state: 0, sema: 0},\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/e2e/assets/controller/slice/slice_event.yaml\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                ],\n            },\n        },\n    }\n    error while running command: exit status 1; Error from server (InternalError): error when creating \"/e2e/assets/controller/slice/slice_event.yaml\": Internal error occurred: failed calling webhook \"msliceconfig.kb.io\": failed to call webhook: Post \"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\": dial tcp 10.96.230.189:443: connect: connection refused\noccurred","children":[{"name":"[It] Events Test Events get recorded for slice config creation Validating events for slice resource quota config creation","uid":"ea0cbd2270b04e12","parentUid":"c763b8d768b2439a491de5d32aebefa0","status":"failed","time":{"start":1693899867000,"stop":1693899875164,"duration":8164},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"c763b8d768b2439a491de5d32aebefa0"},{"name":"Timed out after 31.040s.\nUnexpected error:\n    <*shell.ErrWithCmdOutput | 0xc0006de288>: {\n        Underlying: <*exec.ExitError | 0xc00063a480>{\n            ProcessState: {\n                pid: 6786,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 145725},\n                    Stime: {Sec: 0, Usec: 53314},\n                    Maxrss: 43260,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 2319,\n                    Majflt: 45,\n                    Nswap: 0,\n                    Inblock: 2704,\n                    Oublock: 1064,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 1533,\n                    Nivcsw: 1330,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"E0905 08:09:17.446251    6786 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"E0905 08:09:25.641849    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"E0905 08:09:26.965977    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"E0905 08:09:28.008372    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"Error from server (NotFound): sliceresourcequotaconfigs.controller.kubeslice.io \\\"slice-blue\\\" not found\",\n                    ],\n                },\n            },\n            stderr: {\n                Lines: [\n                    \"E0905 08:09:17.446251    6786 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                    \"E0905 08:09:25.641849    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                    \"E0905 08:09:26.965977    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                    \"E0905 08:09:28.008372    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                    \"Error from server (NotFound): sliceresourcequotaconfigs.controller.kubeslice.io \\\"slice-blue\\\" not found\",\n                ],\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"E0905 08:09:17.446251    6786 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"E0905 08:09:25.641849    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"E0905 08:09:26.965977    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"E0905 08:09:28.008372    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\",\n                        \"Error from server (NotFound): sliceresourcequotaconfigs.controller.kubeslice.io \\\"slice-blue\\\" not found\",\n                    ],\n                },\n            },\n            merged: {\n                Mutex: {state: 0, sema: 0},\n                Lines: [\n                    \"E0905 08:09:17.446251    6786 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the serv...\n\nGomega truncated this representation as it exceeds 'format.MaxLength'.\nConsider having the object provide a custom 'GomegaStringer' representation\nor adjust the parameters in Gomega's 'format' package.\n\nLearn more here: https://onsi.github.io/gomega/#adjusting-output\n\n    error while running command: exit status 1; E0905 08:09:17.446251    6786 memcache.go:287] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\n    E0905 08:09:25.641849    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\n    E0905 08:09:26.965977    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\n    E0905 08:09:28.008372    6786 memcache.go:121] couldn't get resource list for projectcalico.org/v3: the server is currently unable to handle the request\n    Error from server (NotFound): sliceresourcequotaconfigs.controller.kubeslice.io \"slice-blue\" not found\noccurred","children":[{"name":"[It] Slice resource quota Tests ResourceQuota creation tests ResourceQuota should be created once SliceConfig gets created","uid":"814790d867baceff","parentUid":"fe5d63d706862b453cadd25c9d58b809","status":"failed","time":{"start":1693899867000,"stop":1693899929330,"duration":62330},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"fe5d63d706862b453cadd25c9d58b809"},{"name":"Timed out after 500.031s.\nExpected\n    <bool>: false\nto be true","children":[{"name":"[AfterSuite]","uid":"e310d6788a5bbab2","parentUid":"b3546d3b50102c21d0116562c40a3be8","status":"failed","time":{"start":1693899867000,"stop":1693900389139,"duration":522139},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b3546d3b50102c21d0116562c40a3be8"},{"name":"Unexpected error:\n    <*shell.ErrWithCmdOutput | 0xc000017b90>: {\n        Underlying: <*exec.ExitError | 0xc00072f6e0>{\n            ProcessState: {\n                pid: 6892,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 438725},\n                    Stime: {Sec: 0, Usec: 298954},\n                    Maxrss: 112868,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 6980,\n                    Majflt: 19,\n                    Nswap: 0,\n                    Inblock: 3280,\n                    Oublock: 20624,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 1653,\n                    Nivcsw: 3826,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20RBAC%20Tests%20SliceRoleTemplate%20Tests%20Create%20SliceRoleTempalate%20successful%20test:%20Creating%20SliceRoleTempalate%20read-only-role3754015361\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                    ],\n                },\n            },\n            stderr: {\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20RBAC%20Tests%20SliceRoleTemplate%20Tests%20Create%20SliceRoleTempalate%20successful%20test:%20Creating%20SliceRoleTempalate%20read-only-role3754015361\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                ],\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20RBAC%20Tests%20SliceRoleTemplate%20Tests%20Create%20SliceRoleTempalate%20successful%20test:%20Creating%20SliceRoleTempalate%20read-only-role3754015361\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                    ],\n                },\n            },\n            merged: {\n                Mutex: {state: 0, sema: 0},\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20RBAC%20Tests%20SliceRoleTemplate%20Tests%20Create%20SliceRoleTempalate%20successful%20test:%20Creating%20SliceRoleTempalate%20read-only-role3754015361\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                ],\n            },\n        },\n    }\n    error while running command: exit status 1; Error from server (InternalError): error when creating \"/tmp/Slice%20RBAC%20Tests%20SliceRoleTemplate%20Tests%20Create%20SliceRoleTempalate%20successful%20test:%20Creating%20SliceRoleTempalate%20read-only-role3754015361\": Internal error occurred: failed calling webhook \"msliceconfig.kb.io\": failed to call webhook: Post \"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\": dial tcp 10.96.230.189:443: connect: connection refused\noccurred","children":[{"name":"[It] Slice RBAC Tests SliceRoleTemplate Tests Create SliceRoleTempalate successful test: Creating SliceRoleTempalate read-only-role","uid":"c769c51fecb70afd","parentUid":"962fdfcce2a9d996aecdb95eb9e1a79e","status":"failed","time":{"start":1693899867000,"stop":1693899877332,"duration":10332},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"962fdfcce2a9d996aecdb95eb9e1a79e"},{"name":"Unexpected error:\n    <*shell.ErrWithCmdOutput | 0xc000017aa0>: {\n        Underlying: <*exec.ExitError | 0xc00072f240>{\n            ProcessState: {\n                pid: 6878,\n                status: 256,\n                rusage: {\n                    Utime: {Sec: 0, Usec: 353409},\n                    Stime: {Sec: 0, Usec: 263177},\n                    Maxrss: 102340,\n                    Ixrss: 0,\n                    Idrss: 0,\n                    Isrss: 0,\n                    Minflt: 13236,\n                    Majflt: 16,\n                    Nswap: 0,\n                    Inblock: 13016,\n                    Oublock: 20624,\n                    Msgsnd: 0,\n                    Msgrcv: 0,\n                    Nsignals: 0,\n                    Nvcsw: 2442,\n                    Nivcsw: 3064,\n                },\n            },\n            Stderr: nil,\n        },\n        Output: {\n            stdout: {\n                Lines: nil,\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20node%20affinity%20Tests%20SliceNodeAffinity%20tests%20-%20includes%20creation%20and%20deletion%20slice%20node%20affinity%20creation%20success%20test962941551\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                    ],\n                },\n            },\n            stderr: {\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20node%20affinity%20Tests%20SliceNodeAffinity%20tests%20-%20includes%20creation%20and%20deletion%20slice%20node%20affinity%20creation%20success%20test962941551\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                ],\n                merged: {\n                    Mutex: {state: 0, sema: 0},\n                    Lines: [\n                        \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20node%20affinity%20Tests%20SliceNodeAffinity%20tests%20-%20includes%20creation%20and%20deletion%20slice%20node%20affinity%20creation%20success%20test962941551\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                    ],\n                },\n            },\n            merged: {\n                Mutex: {state: 0, sema: 0},\n                Lines: [\n                    \"Error from server (InternalError): error when creating \\\"/tmp/Slice%20node%20affinity%20Tests%20SliceNodeAffinity%20tests%20-%20includes%20creation%20and%20deletion%20slice%20node%20affinity%20creation%20success%20test962941551\\\": Internal error occurred: failed calling webhook \\\"msliceconfig.kb.io\\\": failed to call webhook: Post \\\"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\\\": dial tcp 10.96.230.189:443: connect: connection refused\",\n                ],\n            },\n        },\n    }\n    error while running command: exit status 1; Error from server (InternalError): error when creating \"/tmp/Slice%20node%20affinity%20Tests%20SliceNodeAffinity%20tests%20-%20includes%20creation%20and%20deletion%20slice%20node%20affinity%20creation%20success%20test962941551\": Internal error occurred: failed calling webhook \"msliceconfig.kb.io\": failed to call webhook: Post \"https://kubeslice-controller-webhook-service.kubeslice-controller.svc:443/mutate-controller-kubeslice-io-v1alpha1-sliceconfig?timeout=10s\": dial tcp 10.96.230.189:443: connect: connection refused\noccurred","children":[{"name":"[It] Slice node affinity Tests SliceNodeAffinity tests - includes creation and deletion slice node affinity creation success test","uid":"72050e38879c10a3","parentUid":"e15fd3506ef4e1354f0378a200200d72","status":"failed","time":{"start":1693899867000,"stop":1693899885859,"duration":18859},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e15fd3506ef4e1354f0378a200200d72"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}